import type { Metadata } from "next";
import Link from "next/link";
import ProgramFAQ from "@/components/ProgramFAQ";

export const metadata: Metadata = {
  title: "Personalized Training & Nutrition System | PowerBuilder",
  description:
    "A custom 4-week training and nutrition system built specifically for you by Artur. Fill the questionnaire and receive your program within 48 hours.",
};

const included = [
  {
    icon: (
      <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
      </svg>
    ),
    title: "Custom Training Plan",
    description:
      "A 4-week training program designed around your schedule, equipment, experience level, and specific weak points. Every exercise has a reason.",
  },
  {
    icon: (
      <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M3 6l3 1m0 0l-3 9a5.002 5.002 0 006.001 0M6 7l3 9M6 7l6-2m6 2l3-1m-3 1l-3 9a5.002 5.002 0 006.001 0M18 7l3 9m-3-9l-6-2m0-2v2m0 16V5m0 16H9m3 0h3" />
      </svg>
    ),
    title: "Personalized Nutrition Plan",
    description:
      "Exact calorie and macro targets calculated for your body weight, goal (bulk/cut/maintain), and training intensity. No guessing.",
  },
  {
    icon: (
      <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M13 10V3L4 14h7v7l9-11h-7z" />
      </svg>
    ),
    title: "Strength & Hypertrophy Focus",
    description:
      "Both training adaptations included. Compound strength work on main lifts + hypertrophy accessory work to build the muscle you actually want.",
  },
  {
    icon: (
      <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
      </svg>
    ),
    title: "Recovery Optimization",
    description:
      "Training frequency, rest days, and deload protocols planned around your recovery capacity and sleep quality.",
  },
  {
    icon: (
      <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
      </svg>
    ),
    title: "PDF Delivery — 48h",
    description:
      "Your complete system delivered as a clean, organized PDF within 48 hours of submission. Ready to print or use on any device.",
  },
  {
    icon: (
      <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
      </svg>
    ),
    title: "Built By Artur — Personally",
    description:
      "Not AI-generated. Not a template. Artur personally reads every questionnaire submission and writes every program.",
  },
];

const faqs = [
  {
    question: "How long does it take to receive my program?",
    answer:
      "Within 48 hours of payment and questionnaire submission. Artur personally reviews each submission, so the delivery time reflects the care that goes into every program. You'll receive a PDF directly to your email.",
  },
  {
    question: "What exactly is included?",
    answer:
      "A complete 4-week training plan (all sessions, exercises, sets, reps, and progressive overload built in) + a personalized nutrition plan (daily calorie target, macro breakdown, meal timing guidance). Both tailored specifically to your answers — not a template.",
  },
  {
    question: "Is this program generated by AI?",
    answer:
      "No. Artur personally reads every questionnaire and writes every program. This is why delivery takes up to 48 hours — real coaching takes real time. The questionnaire gives Artur everything he needs to build something that actually fits your situation.",
  },
  {
    question: "What if I'm not satisfied with the program?",
    answer:
      "Contact Artur directly. If something in the program doesn't make sense for your situation or there's a mismatch with what you described in the questionnaire, he'll address it. The goal is a program you can actually execute and get results from.",
  },
  {
    question: "How many questions are in the questionnaire?",
    answer:
      "16 questions covering your profile (age, height, weight, gender), training background (experience, days/week, gym access, bench experience), goals, body assessment (weak and strong points, injuries), and lifestyle (nutrition preference, sleep quality). Takes about 5–8 minutes to complete.",
  },
  {
    question: "Can beginners use the personalized program?",
    answer:
      "Yes. Unlike the static programs which assume at least 6 months of experience, the personalized program is adjusted to wherever you are. If you're earlier in your journey, Artur designs accordingly — realistic loads, appropriate volume, exercises you can execute safely.",
  },
];

export default function PersonalizedPage() {
  return (
    <div className="bg-brand-bg pt-16">
      {/* Hero */}
      <section className="relative py-24 md:py-32 border-b border-brand-border overflow-hidden">
        <div className="absolute top-1/2 right-0 -translate-y-1/2 w-[500px] h-[500px] bg-red-600/6 rounded-full blur-[120px] pointer-events-none" />
        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="max-w-3xl">
            <p className="section-label mb-5">Flagship Offer</p>
            <h1 className="text-5xl sm:text-6xl md:text-7xl font-black uppercase tracking-tight leading-none mb-6">
              Your Program.
              <br />
              <span className="text-red-600">Your Rules.</span>
            </h1>
            <p className="text-zinc-400 text-lg md:text-xl leading-relaxed mb-10 max-w-2xl">
              A complete training and nutrition system built from scratch for your
              body, your goals, and your schedule. Not a template — a real coaching
              product.
            </p>

            <div className="flex flex-col sm:flex-row items-start gap-4">
              <Link href="/questionnaire" className="btn-primary">
                Start Questionnaire
              </Link>
              <div className="flex items-center gap-3 self-center">
                <span className="text-white font-black text-3xl">€99</span>
                <span className="text-zinc-600 text-sm">one-time · 48h delivery</span>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* What's included */}
      <section className="py-24 md:py-32 border-b border-brand-border">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <p className="section-label mb-4">Everything Included</p>
            <h2 className="section-heading">
              One Price.
              <br />
              <span className="text-red-600">Complete System.</span>
            </h2>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-px bg-brand-border">
            {included.map((item, i) => (
              <div key={i} className="bg-brand-bg p-8 flex flex-col gap-4 hover:bg-brand-card transition-colors">
                <div className="text-red-600">{item.icon}</div>
                <h3 className="text-white font-bold text-lg tracking-tight">{item.title}</h3>
                <p className="text-zinc-500 text-sm leading-relaxed">{item.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* How it works */}
      <section className="bg-brand-surface border-b border-brand-border py-24 md:py-32">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <p className="section-label mb-4">Process</p>
            <h2 className="section-heading">
              How It
              <br />
              <span className="text-red-600">Works.</span>
            </h2>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-4 gap-4 md:gap-0">
            {[
              {
                num: "01",
                title: "Fill the Questionnaire",
                description: "16 questions covering your profile, training history, goals, body assessment, and lifestyle. Takes 5–8 minutes.",
              },
              {
                num: "02",
                title: "Complete Payment",
                description: "Pay €99 via PayPal. Your questionnaire answers are automatically sent to Artur upon payment confirmation.",
              },
              {
                num: "03",
                title: "Artur Reviews",
                description: "Artur personally reads your submission, analyzes your data, and writes your custom program. No templates.",
              },
              {
                num: "04",
                title: "Receive Your System",
                description: "Your full training + nutrition PDF is delivered to your email within 48 hours. Ready to start.",
              },
            ].map((step, i) => (
              <div key={i} className="relative flex flex-col p-8 border border-brand-border md:border-r-0 last:border-r md:border-b-0">
                <span className="text-red-600 font-black text-5xl leading-none mb-4 opacity-40">
                  {step.num}
                </span>
                <h3 className="text-white font-black text-lg uppercase tracking-tight mb-3">
                  {step.title}
                </h3>
                <p className="text-zinc-500 text-sm leading-relaxed">{step.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Trust signals */}
      <section className="py-24 md:py-32 border-b border-brand-border">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-px bg-brand-border">
            {[
              { value: "48h", label: "Program Delivery" },
              { value: "16", label: "Questionnaire Questions" },
              { value: "100%", label: "Personally Written" },
              { value: "€99", label: "One-Time, No Subscription" },
            ].map((stat, i) => (
              <div key={i} className="bg-brand-bg p-8 text-center">
                <p className="text-red-600 font-black text-4xl mb-2">{stat.value}</p>
                <p className="text-zinc-500 text-xs uppercase tracking-widest">{stat.label}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* FAQ */}
      <ProgramFAQ faqs={faqs} />

      {/* Bottom CTA */}
      <section className="py-24 md:py-32">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <p className="section-label mb-4">Ready?</p>
          <h2 className="section-heading mb-6">
            Start Your
            <br />
            <span className="text-red-600">Transformation.</span>
          </h2>
          <p className="text-zinc-400 text-lg mb-10">
            Fill the questionnaire. Pay once. Get a system built for you.
            Train smart for 4 weeks.
          </p>
          <Link href="/questionnaire" className="btn-primary">
            Start Questionnaire — €99
          </Link>
          <p className="text-zinc-700 text-xs mt-4">
            PayPal · 48-hour delivery · Personalized by Artur
          </p>
        </div>
      </section>
    </div>
  );
}
