import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import ProgramFAQ from "@/components/ProgramFAQ";

export const metadata: Metadata = {
  title: "Personalized Training & Nutrition System | PowerBuilder",
  description:
    "A custom 4-week training and nutrition system built specifically for you by Artur. Fill the questionnaire and receive your program within 48 hours.",
};

const included = [
  {
    icon: (
      <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
      </svg>
    ),
    title: "Custom Training Plan",
    description:
      "A 4-week training program designed around your schedule, equipment, experience level, and specific weak points. Every exercise has a reason.",
  },
  {
    icon: (
      <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M3 6l3 1m0 0l-3 9a5.002 5.002 0 006.001 0M6 7l3 9M6 7l6-2m6 2l3-1m-3 1l-3 9a5.002 5.002 0 006.001 0M18 7l3 9m-3-9l-6-2m0-2v2m0 16V5m0 16H9m3 0h3" />
      </svg>
    ),
    title: "Personalized Nutrition Plan",
    description:
      "Exact calorie and macro targets calculated for your body weight, goal, and training intensity. No guessing, no generic advice.",
  },
  {
    icon: (
      <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M13 10V3L4 14h7v7l9-11h-7z" />
      </svg>
    ),
    title: "Strength & Hypertrophy Focus",
    description:
      "Compound strength on main lifts + hypertrophy accessory work. Both adaptations, one system — built specifically for powerbuilding.",
  },
  {
    icon: (
      <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
      </svg>
    ),
    title: "Recovery Optimization",
    description:
      "Training frequency, rest days, and deload protocols planned around your recovery capacity and sleep quality.",
  },
  {
    icon: (
      <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
      </svg>
    ),
    title: "PDF Delivery — 48h",
    description:
      "Your complete system delivered as a clean, organized PDF within 48 hours of submission. Ready to use on any device.",
  },
  {
    icon: (
      <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
      </svg>
    ),
    title: "Written By Artur — Personally",
    description:
      "Not AI-generated. Not a template. Artur reads every submission and writes every program himself.",
  },
];

const faqs = [
  {
    question: "How long does it take to receive my program?",
    answer:
      "Within 48 hours of payment and questionnaire submission. Artur personally reviews each submission, so the delivery time reflects the care that goes into every program. You'll receive a PDF directly to your email.",
  },
  {
    question: "What exactly is included?",
    answer:
      "A complete 4-week training plan (all sessions, exercises, sets, reps, and progressive overload built in) + a personalized nutrition plan (daily calorie target, macro breakdown, meal timing guidance). Both tailored specifically to your answers — not a template.",
  },
  {
    question: "Is this program generated by AI?",
    answer:
      "No. Artur personally reads every questionnaire and writes every program. This is why delivery takes up to 48 hours — real coaching takes real time.",
  },
  {
    question: "What if I'm not satisfied with the program?",
    answer:
      "Contact Artur directly. If something in the program doesn't make sense for your situation or there's a mismatch with what you described in the questionnaire, he'll address it.",
  },
  {
    question: "How many questions are in the questionnaire?",
    answer:
      "16 questions covering your profile (age, height, weight, gender), training background (experience, days/week, gym access, bench experience), goals, body assessment, and lifestyle. Takes about 5–8 minutes.",
  },
  {
    question: "Can beginners use the personalized program?",
    answer:
      "Yes. Unlike the static programs, the personalized program is adjusted to wherever you are. If you're earlier in your journey, Artur designs accordingly — realistic loads, appropriate volume, exercises you can execute safely.",
  },
];

export default function PersonalizedPage() {
  return (
    <div className="bg-brand-bg pt-16">

      {/* ── Hero ──────────────────────────────────────────────────────── */}
      <section className="relative py-24 md:py-36 border-b border-brand-border overflow-hidden">
        {/* Background glow */}
        <div className="absolute top-1/2 right-0 -translate-y-1/2 w-[600px] h-[600px] bg-red-600/5 rounded-full blur-[140px] pointer-events-none" />
        <div className="absolute bottom-0 left-1/4 w-[300px] h-[300px] bg-red-600/4 rounded-full blur-[100px] pointer-events-none" />

        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="max-w-3xl">
            {/* Badge */}
            <div className="inline-flex items-center gap-2 border border-red-600/30 bg-red-600/5 px-3 py-1.5 mb-8">
              <span className="w-1.5 h-1.5 rounded-full bg-red-500 animate-pulse" />
              <span className="text-red-400 text-[10px] font-bold uppercase tracking-[0.2em]">
                Flagship Offer · Not a Template
              </span>
            </div>

            <h1 className="text-5xl sm:text-6xl md:text-7xl font-black uppercase tracking-tight leading-none mb-6">
              Built For You.
              <br />
              <span className="text-red-600">Only You.</span>
            </h1>
            <p className="text-zinc-400 text-lg md:text-xl leading-relaxed mb-10 max-w-2xl">
              A complete training and nutrition system written from scratch by Artur
              — for your body, your goals, your schedule. No templates. No guesswork.
            </p>

            <div className="flex flex-col sm:flex-row items-start sm:items-center gap-5 mb-10">
              <Link href="/questionnaire" className="btn-primary text-sm px-10 py-4">
                Start Questionnaire →
              </Link>
              <div>
                <span className="text-white font-black text-3xl">€99</span>
                <span className="text-zinc-600 text-sm ml-2">one-time</span>
              </div>
            </div>

            {/* Quick trust row */}
            <div className="flex flex-wrap gap-x-6 gap-y-2">
              {["48h delivery", "PayPal secure checkout", "Personally written by Artur"].map((t) => (
                <div key={t} className="flex items-center gap-2">
                  <svg className="w-3.5 h-3.5 text-red-600 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M5 13l4 4L19 7" />
                  </svg>
                  <span className="text-zinc-500 text-xs">{t}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* ── Stats bar ─────────────────────────────────────────────────── */}
      <section className="bg-brand-surface border-b border-brand-border">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-2 md:grid-cols-4 divide-x divide-y md:divide-y-0 divide-brand-border">
            {[
              { value: "48h", label: "Program Delivery" },
              { value: "16", label: "Questionnaire Questions" },
              { value: "100%", label: "Personally Written" },
              { value: "€99", label: "One-Time · No Subscription" },
            ].map((stat, i) => (
              <div key={i} className="py-8 px-6 text-center">
                <p className="text-red-600 font-black text-4xl mb-1.5">{stat.value}</p>
                <p className="text-zinc-600 text-xs uppercase tracking-widest">{stat.label}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── What's included ───────────────────────────────────────────── */}
      <section className="py-24 md:py-32 border-b border-brand-border">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <p className="section-label mb-4">Everything Included</p>
            <h2 className="section-heading">
              One Price.
              <br />
              <span className="text-red-600">Complete System.</span>
            </h2>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-px bg-brand-border">
            {included.map((item, i) => (
              <div key={i} className="bg-brand-bg p-8 flex flex-col gap-4 hover:bg-brand-card transition-colors duration-200 group">
                <div className="text-red-600 group-hover:scale-110 transition-transform duration-200 w-fit">
                  {item.icon}
                </div>
                <h3 className="text-white font-bold text-base tracking-tight">{item.title}</h3>
                <p className="text-zinc-500 text-sm leading-relaxed">{item.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Built by Artur ────────────────────────────────────────────── */}
      <section className="bg-brand-surface border-b border-brand-border py-24 md:py-32">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-12 md:gap-20 items-center">

            {/* Image side */}
            <div className="flex justify-center md:justify-end">
              <div className="relative">
                <div className="absolute -inset-4 bg-red-600/8 blur-2xl rounded-full" />
                <div className="relative w-64 h-64 md:w-80 md:h-80 rounded-full overflow-hidden border-2 border-red-600/30 shadow-2xl shadow-red-900/20">
                  <Image
                    src="/Profile.jpg"
                    alt="Artur Mehmeti — PowerBuilder Coach"
                    fill
                    className="object-cover object-top"
                    sizes="(max-width: 768px) 256px, 320px"
                  />
                </div>
                {/* Credential badge */}
                <div className="absolute -bottom-4 left-1/2 -translate-x-1/2 bg-brand-card border border-brand-border px-5 py-2.5 whitespace-nowrap">
                  <p className="text-white font-black text-xs uppercase tracking-widest text-center">
                    Artur Mehmeti
                  </p>
                  <p className="text-red-500 text-[10px] uppercase tracking-widest text-center mt-0.5">
                    PowerBuilder Coach · Berlin
                  </p>
                </div>
              </div>
            </div>

            {/* Text side */}
            <div className="md:pl-4 mt-8 md:mt-0">
              <p className="section-label mb-5">The Coach</p>
              <h2 className="section-heading mb-6">
                Written By
                <br />
                <span className="text-red-600">Artur.</span>
              </h2>
              <div className="flex flex-col gap-5 text-zinc-400 leading-relaxed">
                <p>
                  Every program is written by Artur personally. He reads your questionnaire,
                  analyzes your data, and builds a system that matches exactly where you are
                  and where you want to go.
                </p>
                <p>
                  This is not AI-generated. This is not a template with your name on it.
                  It takes real time because it requires real attention — and that is
                  precisely what you are paying for.
                </p>
              </div>

              <div className="mt-8 flex flex-col gap-3">
                {[
                  "20 years old, Berlin-based athlete",
                  "Trained in powerbuilding for years",
                  "Every submission reviewed personally",
                  "Programs capped — no factory output",
                ].map((point) => (
                  <div key={point} className="flex items-start gap-3">
                    <div className="w-1.5 h-1.5 rounded-full bg-red-600 mt-1.5 shrink-0" />
                    <span className="text-zinc-400 text-sm">{point}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ── How it works ──────────────────────────────────────────────── */}
      <section className="py-24 md:py-32 border-b border-brand-border">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <p className="section-label mb-4">Process</p>
            <h2 className="section-heading">
              How It
              <br />
              <span className="text-red-600">Works.</span>
            </h2>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-4 gap-px bg-brand-border">
            {[
              {
                num: "01",
                title: "Fill the Questionnaire",
                description: "16 questions covering your profile, training history, goals, body assessment, and lifestyle. Takes 5–8 minutes.",
              },
              {
                num: "02",
                title: "Complete Payment",
                description: "Pay €99 via PayPal. Secure checkout. Your questionnaire is submitted to Artur upon payment confirmation.",
              },
              {
                num: "03",
                title: "Artur Reviews",
                description: "Artur personally reads your submission, analyzes your data, and writes your custom program. No templates.",
              },
              {
                num: "04",
                title: "Receive Your System",
                description: "Your full training + nutrition PDF is delivered to your email within 48 hours. Open it and start Day 1.",
              },
            ].map((step, i) => (
              <div key={i} className="bg-brand-bg p-8 flex flex-col hover:bg-brand-card transition-colors duration-200">
                <span className="text-red-600 font-black text-6xl leading-none mb-5 opacity-30">
                  {step.num}
                </span>
                <h3 className="text-white font-black text-base uppercase tracking-tight mb-3">
                  {step.title}
                </h3>
                <p className="text-zinc-500 text-sm leading-relaxed">{step.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Why personalized ──────────────────────────────────────────── */}
      <section className="bg-brand-surface border-b border-brand-border py-24 md:py-32">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <p className="section-label mb-4">The Difference</p>
            <h2 className="section-heading">
              Generic vs.
              <br />
              <span className="text-red-600">Personalized.</span>
            </h2>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-px bg-brand-border max-w-4xl mx-auto">
            {/* Generic column */}
            <div className="bg-brand-bg p-8 md:p-10">
              <p className="text-zinc-600 text-xs font-bold uppercase tracking-widest mb-6">
                Generic Program
              </p>
              <div className="flex flex-col gap-4">
                {[
                  "Built for the average person — not you",
                  "Same reps, sets, and exercises for everyone",
                  "Ignores your weak points and injury history",
                  "Nutrition is an afterthought or missing entirely",
                  "No accountability — just a PDF download",
                ].map((item) => (
                  <div key={item} className="flex items-start gap-3">
                    <svg className="w-4 h-4 text-zinc-700 mt-0.5 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                    </svg>
                    <span className="text-zinc-600 text-sm leading-relaxed">{item}</span>
                  </div>
                ))}
              </div>
            </div>

            {/* Personalized column */}
            <div className="bg-brand-card border-l border-red-600/20 p-8 md:p-10">
              <div className="h-0.5 bg-red-600 -mt-8 -mx-8 md:-mx-10 mb-6" />
              <p className="text-red-500 text-xs font-bold uppercase tracking-widest mb-6">
                Artur's Personalized System
              </p>
              <div className="flex flex-col gap-4">
                {[
                  "Written for your exact body, goals, and schedule",
                  "Every exercise chosen with your data in mind",
                  "Weak points targeted, injuries worked around",
                  "Nutrition targets calculated for your specific situation",
                  "Artur reads your submission and writes it personally",
                ].map((item) => (
                  <div key={item} className="flex items-start gap-3">
                    <svg className="w-4 h-4 text-red-600 mt-0.5 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M5 13l4 4L19 7" />
                    </svg>
                    <span className="text-zinc-300 text-sm leading-relaxed">{item}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ── Guarantee ─────────────────────────────────────────────────── */}
      <section className="py-24 md:py-32 border-b border-brand-border">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <div className="inline-flex items-center justify-center w-14 h-14 border border-red-600/30 bg-red-600/5 mb-8">
            <svg className="w-7 h-7 text-red-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
            </svg>
          </div>
          <p className="section-label mb-4">Our Commitment</p>
          <h2 className="section-heading mb-6">
            If It Doesn&apos;t Fit.
            <br />
            <span className="text-red-600">Artur Fixes It.</span>
          </h2>
          <p className="text-zinc-400 text-lg leading-relaxed max-w-xl mx-auto">
            If something in your program doesn&apos;t match what you described in the
            questionnaire, contact Artur directly. He will address it — because the
            goal is a program you can actually execute and get results from.
          </p>
        </div>
      </section>

      {/* ── FAQ ───────────────────────────────────────────────────────── */}
      <ProgramFAQ faqs={faqs} />

      {/* ── Bottom CTA ────────────────────────────────────────────────── */}
      <section className="relative py-24 md:py-36 overflow-hidden">
        <div className="absolute inset-0 bg-brand-surface" />
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[500px] h-[500px] bg-red-600/6 rounded-full blur-[120px] pointer-events-none" />

        <div className="relative max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <p className="section-label mb-4">Ready?</p>
          <h2 className="section-heading mb-6">
            Start Your
            <br />
            <span className="text-red-600">Transformation.</span>
          </h2>
          <p className="text-zinc-400 text-lg mb-10 leading-relaxed">
            Fill the questionnaire. Pay once. Get a system built for exactly who you are.
          </p>
          <Link href="/questionnaire" className="btn-primary text-sm px-12 py-5">
            Start Questionnaire — €99 →
          </Link>
          <p className="text-zinc-700 text-xs mt-5">
            PayPal · 48-hour delivery · Personally written by Artur
          </p>
        </div>
      </section>

    </div>
  );
}
